#app:
#id: springboot-apollo
#apollo:
#meta: http://192.168.120.101:8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douluo?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn:
      itcast:
        study: debug
server:
  port: 8888
  servlet:
    session:
      timeout: 10s

